# Generated by Django 5.1.4 on 2025-04-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfume_princess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='princess',
            new_name='prices',
        ),
    ]
