# Generated by Django 5.1.4 on 2025-04-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_princess_perfume_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchengine',
            options={'verbose_name_plural': 'Search Engines'},
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='grp',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='prices',
        ),
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfume_images/'),
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
