# Generated by Django 5.1.4 on 2025-04-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_searchengine_options_rename_grp_perfume_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfume_images/')),
                ('available', models.BooleanField(default=True)),
                ('grams', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight of the product in grams', max_digits=5)),
            ],
        ),
    ]
