# Generated by Django 5.1.4 on 2025-04-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='group',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='size',
        ),
        migrations.AddField(
            model_name='perfume',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='grams',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight of the product in grams', max_digits=5),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
