# Generated by Django 5.1.4 on 2025-04-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_product_remove_perfume_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='category',
            field=models.CharField(choices=[('Designers_Perfume_Oil', 'Designers_Perfume_Oil'), ('Suratti_Perfume_Oils', 'Suratti_Perfume_Oils'), ('Naseem_Oils', 'Naseem_Oils')], default='eixt', max_length=150),
            preserve_default=False,
        ),
    ]
